--Create Table EmployeeDemographics
--(EmployeeID int,
--FirstName varchar(50),
--LastName varchar(50),
--Age int,
--Gender varchar(50)
--)

--Create Table EmployeeSalary
--(EmployeeID int, 
--JobTitle varchar(50),
--Salary int)
